version: '3.5'

services:

  postgres:
    container_name: postgres
    build: ./database
    env_file:
      - .env
    networks:
      - warper-network
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    networks:
      - warper-network
    ports:
      - "5000:5000"
      - "5555:5555"
    restart: unless-stopped
    depends_on:
      - postgres  

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    networks:
      - warper-network
    ports:
      - "3000:3000"
    depends_on:
      - postgres  
    restart: unless-stopped

networks:
  warper-network:
    name: warper-network
    driver: bridge
